[project]
name = "training_api"
version = "0.1.0"
description = "API that trains models using mlflow"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlflow>=3.5.1",
    "pandas>=2.2",
    "river>=0.22.0",
]
