[project]
name = "models_server"
version = "0.1.0"
description = "API that serves trained models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.0",
    "mlflow>=3.5.1",
    "uvicorn>=0.38.0",
]
