name: Deploy (Docker Compose)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-mlflow-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Set lowercase image name
        id: image-name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mlflow-server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/mlflow-server/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-mlflow-server:latest
            ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-mlflow-server:${{ github.sha }}
            

  build-training-api-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Set lowercase image name
        id: image-name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push training api image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/training_api/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-training-api:latest
            ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-training-api:${{ github.sha }}
            

  build-inference-api-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Set lowercase image name
        id: image-name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push inference api image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/inference_api/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-inference-api:latest
            ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-inference-api:${{ github.sha }}


  deploy-mlflow-and-training-api:
    runs-on: ubuntu-latest
    needs:
      - build-mlflow-container
      - build-training-api-container
    steps:
      - uses: actions/checkout@v5

      - name: Set lowercase image name
        id: image-name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
          
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
          echo "${{ secrets.MLFLOW_DEPLOY_SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.MLFLOW_DEPLOY_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Copy docker compose files via SCP
        run: |
          scp -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              mlflow.compose.v1.yml \
              ${{ secrets.MLFLOW_DEPLOY_SERVER_USER }}@${{ secrets.MLFLOW_DEPLOY_SERVER_HOST }}:/home/${{ secrets.MLFLOW_DEPLOY_SERVER_USER }}/

      - name: Deploy over SSH
        env:
          IMAGE_NAME: ${{ steps.image-name.outputs.IMAGE_NAME }}
        run: |
          ssh -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              ${{ secrets.MLFLOW_DEPLOY_SERVER_USER }}@${{ secrets.MLFLOW_DEPLOY_SERVER_HOST }} \
              bash -s << 'ENDSSH'
            set -e
          
            echo "Deploying to MLFlow Deploy Server..."
            
            # log in to registry
            echo ${{ secrets.GITHUB_TOKEN }} | \
              docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker-compose pull
            docker compose down || true
            docker-compose -f mlflow.compose.v1.yml up -d
            
            echo "Deployment successful!"
          
          ENDSSH


  deploy-inference-api:
    runs-on: ubuntu-latest
    needs: build-inference-api-container
    steps:
      - uses: actions/checkout@v5

      - name: Set lowercase image name
        id: image-name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p "$HOME/.ssh"
          chmod 700 "$HOME/.ssh"
          echo "${{ secrets.API_DEPLOY_SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.API_DEPLOY_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Copy docker compose files via SCP
        run: |
          scp -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              inference.compose.v1.yml \
              ${{ secrets.API_DEPLOY_SERVER_USER }}@${{ secrets.API_DEPLOY_SERVER_HOST }}:/home/${{ secrets.API_DEPLOY_SERVER_USER }}/

      - name: Deploy over SSH
        env:
          IMAGE_NAME: ${{ steps.image-name.outputs.IMAGE_NAME }}
        run: |
          ssh -i ~/.ssh/deploy_key \
              -o StrictHostKeyChecking=no \
              ${{ secrets.API_DEPLOY_SERVER_USER }}@${{ secrets.API_DEPLOY_SERVER_HOST }} \
              bash -s << 'ENDSSH'
            set -e
          
            echo "Deploying to API Deploy Server..."
            
            # log in to registry
            echo ${{ secrets.GITHUB_TOKEN }} | \
              docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker-compose pull
            docker compose down || true
            docker compose -f inference.compose.v1.yml up -d
            
            echo "Deployment successful!"
          
          ENDSSH
