name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-mlflow-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Set lowercase image name
        id: image-name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mlflow-server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/mlflow-server/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-mlflow-server:latest
            ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-mlflow-server:${{ github.sha }}


  deploy-mlflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set lowercase image name
        id: image-name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
          
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}

      - name: SSH to MLFLow Deployment Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.MLFLOW_DEPLOY_SERVER_HOST }}
          username: ${{ secrets.MLFLOW_DEPLOY_SERVER_USER }}
          key: ${{ secrets.MLFLOW_DEPLOY_SERVER_SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying to MLFlow Deploy Server..."
            
            # log in to registry
            echo ${{ secrets.GITHUB_TOKEN }} | \
              docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # pull container and deploy
            docker pull ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-mlflow-server:latest
            docker stop mlflow-server || true
            docker rm mlflow-server || true
            docker run -d --name mlflow-server \
              --restart unless-stopped \
              -p 5050:5050 \
              -v ~/mlruns:/mlflow/mlruns \
              -v ~/mlflow_data:/mlflow \
              -e BACKEND_STORE_URI=sqlite:///mlflow/mlflow.db
              ${{ env.DOCKER_REGISTRY }}/${{ steps.image-name.outputs.IMAGE_NAME }}-mlflow-server:latest
            
            echo "Deployment successful!"
